dofile(debug.getinfo(1, "S").source:gsub("@", ""):match("^(.*)/[^/]+$") .. "/helpers.lua")
local c = require("the-vimmer.ui.common")

local function char_width(s)
  return #(s:gsub("[\194-\223][\128-\191]", "_")
            :gsub("[\224-\239][\128-\191][\128-\191]", "_")
            :gsub("[\240-\247][\128-\191][\128-\191][\128-\191]", "_"))
end

describe("ui.common.format_key", function()
  it("maps escape", function()
    assert.equal("<Esc>", c.format_key("\27"))
  end)
  it("maps cr and lf to <CR>", function()
    assert.equal("<CR>", c.format_key("\r"))
    assert.equal("<CR>", c.format_key("\n"))
  end)
  it("maps tab, space, backspace", function()
    assert.equal("<Tab>", c.format_key("\t"))
    assert.equal("<Spc>", c.format_key(" "))
    assert.equal("<BS>", c.format_key("\x08"))
  end)
  it("passes through plain chars", function()
    assert.equal("a", c.format_key("a"))
    assert.equal("Z", c.format_key("Z"))
  end)
end)

describe("ui.common.mutator_summary_line", function()
  it("returns nil for empty input", function()
    assert.is_nil(c.mutator_summary_line(nil))
    assert.is_nil(c.mutator_summary_line({}))
  end)
  it("renders a single known mutator with its label", function()
    assert.equal("  Mutators: Iron", c.mutator_summary_line({ "iron" }))
  end)
  it("joins multiple mutators with comma-space", function()
    assert.equal("  Mutators: Iron, Glass, Rush",
      c.mutator_summary_line({ "iron", "glass", "rush" }))
  end)
  it("falls back to the raw name for unknown mutators", function()
    assert.equal("  Mutators: foo", c.mutator_summary_line({ "foo" }))
  end)
end)

describe("ui.common.pad_row", function()
  it("pads short content out to width", function()
    assert.equal("║hi    ║", c.pad_row("hi", 8))
  end)
  it("leaves content alone when it equals inner width", function()
    assert.equal("║abcd║", c.pad_row("abcd", 6))
  end)
  it("does not negative-pad when content overflows", function()
    assert.equal("║toolong║", c.pad_row("toolong", 6))
  end)
end)

describe("ui.common.make_border", function()
  it("returns top/sep/bot strings of the given character width", function()
    local b = c.make_border(10)
    assert.equal(10, char_width(b.top))
    assert.equal(10, char_width(b.sep))
    assert.equal(10, char_width(b.bot))
  end)
  it("uses sharp corner characters by default", function()
    local b = c.make_border(10)
    assert.is_truthy(b.top:match("^╔"))
    assert.is_truthy(b.top:match("╗$"))
    assert.is_truthy(b.sep:match("^╠"))
    assert.is_truthy(b.sep:match("╣$"))
    assert.is_truthy(b.bot:match("^╚"))
    assert.is_truthy(b.bot:match("╝$"))
  end)
  it("supports rounded corners when requested", function()
    local b = c.make_border(10, "rounded")
    assert.is_truthy(b.top:match("^╭"))
    assert.is_truthy(b.top:match("╮$"))
    assert.is_truthy(b.sep:match("^├"))
    assert.is_truthy(b.sep:match("┤$"))
    assert.is_truthy(b.bot:match("^╰"))
    assert.is_truthy(b.bot:match("╯$"))
    local narrow = c.make_border(8, "rounded")
    assert.equal("│hi    │", narrow.row("hi"))
  end)
  it("reads border style from plugin config", function()
    package.loaded["the-vimmer"] = { config = { border = "rounded" } }
    assert.equal("rounded", c.current_border_style())
    assert.is_truthy(c.make_border(12).top:match("^╭"))
    package.loaded["the-vimmer"] = nil
  end)
  it("returns a row function that pads through pad_row", function()
    local b = c.make_border(8)
    assert.equal("║hi    ║", b.row("hi"))
  end)
end)

describe("ui.common.spread_row", function()
  it("places right text at the end of the inner width", function()
    local row = c.spread_row("left", "right", 20)
    assert.is_truthy(row:match("left"))
    assert.is_truthy(row:match("right$") or row:match("right"))
  end)
end)

describe("ui.common.truncate", function()
  it("appends ellipsis when truncating", function()
    assert.equal("hel...", c.truncate("hello world", 6))
  end)
  it("returns short strings unchanged", function()
    assert.equal("hi", c.truncate("hi", 10))
  end)
end)

describe("ui.common.map helpers", function()
  it("builds a stats line with streak", function()
    local row = c.map_stats_line(5, 10, 3, 40)
    assert.is_truthy(row:match("5/10 rooms cleared"))
    assert.is_truthy(row:match("streak 3"))
  end)
  it("omits streak when zero", function()
    local row = c.map_stats_line(0, 10, 0, 40)
    assert.is_nil(row:match("streak"))
  end)
  it("formats boss hints by state", function()
    local boss = { id = "x" }
    assert.equal("boss ✓", c.map_boss_hint(boss, true, false, 8, 10))
    assert.equal("boss ready", c.map_boss_hint(boss, false, true, 8, 10))
    assert.is_truthy(c.map_boss_hint(boss, false, false, 4, 10):match("→ boss"))
  end)
  it("builds tier header with progress bar", function()
    local row = c.map_tier_header("BEGINNER", 2, 5, 6, "boss ready", 50)
    assert.is_truthy(row:match("BEGINNER"))
    assert.is_truthy(row:match("2/5"))
    assert.is_truthy(row:match("boss ready"))
  end)
end)

describe("ui.common.tier_room_bar", function()
  it("is all empty when nothing is cleared", function()
    assert.equal("[" .. string.rep("░", 8) .. "]", c.tier_room_bar(0, 5, 8))
  end)
  it("is all filled when fully cleared", function()
    assert.equal("[" .. string.rep("█", 8) .. "]", c.tier_room_bar(5, 5, 8))
  end)
  it("rounds proportional fill to nearest block", function()
    assert.equal("[" .. string.rep("█", 4) .. string.rep("░", 4) .. "]",
      c.tier_room_bar(2, 4, 8))
  end)
  it("returns an all-empty bar when total is zero", function()
    assert.equal("[" .. string.rep("░", 8) .. "]", c.tier_room_bar(0, 0, 8))
  end)
  it("defaults bar_len to 8 when omitted", function()
    assert.equal("[░░░░░░░░]", c.tier_room_bar(0, 0))
  end)
end)

describe("ui.common.game chrome", function()
  it("wraps fill in brackets", function()
    assert.equal("[████░░░░]", c.bracket_bar(4, 8, 8))
  end)
  it("derives level from xp", function()
    assert.equal(1, c.game_level(0))
    assert.equal(2, c.game_level(120))
  end)
  it("centers a section title", function()
    local row = c.game_section("QUICK PLAY", 40)
    assert.is_truthy(row:match("QUICK PLAY"))
    assert.is_truthy(row:match("══"))
  end)
  it("formats game footer bindings", function()
    local row = c.game_footer({ { "ENTER", "play" }, { "Q", "quit" } })
    assert.is_truthy(row:match("%[ENTER%] play"))
    assert.is_truthy(row:match("%[Q%] quit"))
  end)
  it("marks selected menu rows with a cursor", function()
    assert.is_truthy(c.game_menu_row(true, "○", "Room", 20):match("▶"))
    assert.is_truthy(c.game_menu_row(false, "○", "Room", 20):match("○"))
  end)
end)

describe("ui.common.fmt_run_seconds", function()
  it("formats with one decimal and a trailing s", function()
    assert.equal("0.0s", c.fmt_run_seconds(0))
    assert.equal("12.3s", c.fmt_run_seconds(12.3))
    assert.equal("47.0s", c.fmt_run_seconds(47))
  end)
end)

describe("ui.common.streak_milestone_phrase", function()
  it("returns nil for sub-3 streaks", function()
    assert.is_nil(c.streak_milestone_phrase(0))
    assert.is_nil(c.streak_milestone_phrase(2))
  end)
  it("returns the right phrase at each threshold", function()
    assert.equal("Three in a row — streak bonus territory.",
      c.streak_milestone_phrase(3))
    assert.equal("Five deep — rhythm locked in.",
      c.streak_milestone_phrase(5))
    assert.equal("Double digits — you're flying.",
      c.streak_milestone_phrase(10))
    assert.equal("Dungeon legend — unreal streak.",
      c.streak_milestone_phrase(20))
  end)
  it("returns the highest matching tier for streaks above 20", function()
    assert.equal("Dungeon legend — unreal streak.",
      c.streak_milestone_phrase(42))
  end)
end)

describe("ui.common.xp_bar", function()
  it("is all empty at zero xp", function()
    assert.equal("[" .. string.rep("░", 8) .. "]", c.xp_bar(0, 8))
  end)
  it("is all filled at max xp (1000)", function()
    assert.equal("[" .. string.rep("▓", 8) .. "]", c.xp_bar(1000, 8))
  end)
  it("clamps to width when xp exceeds max", function()
    assert.equal("[" .. string.rep("▓", 8) .. "]", c.xp_bar(99999, 8))
  end)
  it("renders proportional fill", function()
    assert.equal("[" .. string.rep("▓", 4) .. string.rep("░", 4) .. "]",
      c.xp_bar(500, 8))
  end)
end)

describe("ui.common.build_optimal_lines", function()
  it("returns one short line for a regular room", function()
    local room = { optimal_keystrokes = { "d", "w" } }
    local out = c.build_optimal_lines(room, 80)
    assert.equal(1, #out)
    assert.equal("  d w", out[1])
  end)
  it("renders one line per phase for a boss room", function()
    local room = {
      is_boss = true,
      phases = {
        { optimal_keystrokes = { "d", "w" } },
        { optimal_keystrokes = { "y", "y", "p" } },
      },
    }
    local out = c.build_optimal_lines(room, 80)
    assert.equal(2, #out)
    assert.equal("  P1: d w", out[1])
    assert.equal("  P2: y y p", out[2])
  end)
  it("wraps long sequences to multiple lines", function()
    local ks = {}
    for i = 1, 30 do ks[i] = "x" end
    local room = { optimal_keystrokes = ks }
    local out = c.build_optimal_lines(room, 20)
    assert.is_true(#out >= 2)
    for _, ln in ipairs(out) do
      assert.is_true(#ln <= 20)
    end
  end)
end)

describe("ui.common.wrap_teach_text", function()
  it("returns an empty list for empty input", function()
    assert.same({}, c.wrap_teach_text("", 20))
    assert.same({}, c.wrap_teach_text(nil, 20))
  end)
  it("keeps short text on one line", function()
    assert.same({ "hello world" }, c.wrap_teach_text("hello world", 20))
  end)
  it("wraps at word boundaries", function()
    local out = c.wrap_teach_text("one two three four five", 10)
    assert.is_true(#out >= 2)
    for _, ln in ipairs(out) do
      assert.is_true(#ln <= 10)
    end
  end)
  it("trims leading and trailing whitespace", function()
    assert.same({ "x" }, c.wrap_teach_text("   x   ", 10))
  end)
end)

describe("ui.common.expand_keys", function()
  it("splits a multi-char token into single keys", function()
    assert.same({ "c", "i", "w" }, c.expand_keys({ "ciw" }))
  end)

  it("keeps <...> notation as one key", function()
    assert.same({ "<Esc>" }, c.expand_keys({ "<Esc>" }))
  end)

  it("expands a mixed sequence", function()
    assert.same({ "j", "$", "r", "5" }, c.expand_keys({ "j", "$", "r", "5" }))
  end)

  it("handles a token with text and a notation key", function()
    assert.same({ "c", "i", "w", "x", "<Esc>" },
      c.expand_keys({ "ciw", "x", "<Esc>" }))
  end)

  it("returns empty for empty input", function()
    assert.same({}, c.expand_keys({}))
    assert.same({}, c.expand_keys(nil))
  end)
end)

describe("ui.common.pick_baseline", function()
  it("returns the single path when there are no alternates", function()
    local ctx = { optimal_keystrokes = { "j", "$", "r", "5" } }
    local b = c.pick_baseline(ctx)
    assert.same({ "j", "$", "r", "5" }, b.tokens)
    assert.equals(4, b.expanded_count)
  end)

  it("picks the alternate with fewest expanded keys", function()
    local ctx = {
      optimal_keystrokes = { "j", "l", "l", "l", "r", "5" },  -- 6
      optimal_keystrokes_alternates = { { "j", "$", "r", "5" } },  -- 4
    }
    local b = c.pick_baseline(ctx)
    assert.same({ "j", "$", "r", "5" }, b.tokens)
    assert.equals(4, b.expanded_count)
  end)

  it("counts multi-char tokens by expanded length", function()
    local ctx = { optimal_keystrokes = { "ciw", "x", "<Esc>" } }  -- 3+1+1 = 5
    local b = c.pick_baseline(ctx)
    assert.equals(5, b.expanded_count)
  end)

  it("breaks ties in favor of the primary", function()
    local ctx = {
      optimal_keystrokes = { "a", "b" },
      optimal_keystrokes_alternates = { { "c", "d" } },
    }
    assert.same({ "a", "b" }, c.pick_baseline(ctx).tokens)
  end)

  it("returns nil when there is no sequence", function()
    assert.is_nil(c.pick_baseline({}))
  end)
end)

describe("ui.common.wrap_keys", function()
  it("keeps a short list on one line", function()
    local out = c.wrap_keys({ "j", "$", "r", "5" }, 40)
    assert.equals(1, #out)
    assert.equals("    j $ r 5", out[1])
  end)

  it("wraps when over width", function()
    local parts = {}
    for _ = 1, 30 do parts[#parts + 1] = "l" end
    local out = c.wrap_keys(parts, 20)
    assert.is_true(#out > 1)
    for _, ln in ipairs(out) do assert.is_true(#ln <= 20) end
  end)

  it("returns empty for empty input", function()
    assert.same({}, c.wrap_keys({}, 40))
  end)
end)

describe("ui.common.pb_line", function()
  it("formats both keys and time", function()
    assert.equals("  PB: 4 keys · 8.0s", c.pb_line({ keys = 4, seconds = 8 }))
  end)

  it("shows keys only when seconds is missing", function()
    assert.equals("  PB: 4 keys", c.pb_line({ keys = 4 }))
  end)

  it("shows time only when keys is missing", function()
    assert.equals("  PB: 8.0s", c.pb_line({ seconds = 8 }))
  end)

  it("returns nil when neither side is present", function()
    assert.is_nil(c.pb_line({}))
    assert.is_nil(c.pb_line({ keys = 0, seconds = 0 }))
  end)

  it("returns nil for a non-table argument", function()
    assert.is_nil(c.pb_line(nil))
    assert.is_nil(c.pb_line("x"))
  end)
end)
