dofile(debug.getinfo(1, "S").source:gsub("@", ""):match("^(.*)/[^/]+$") .. "/helpers.lua")
local c = require("the-vimmer.ui.common")

local function char_width(s)
  return #(s:gsub("[\194-\223][\128-\191]", "_")
            :gsub("[\224-\239][\128-\191][\128-\191]", "_")
            :gsub("[\240-\247][\128-\191][\128-\191][\128-\191]", "_"))
end

describe("ui.common.format_key", function()
  it("maps escape", function()
    assert.equal("<Esc>", c.format_key("\27"))
  end)
  it("maps cr and lf to <CR>", function()
    assert.equal("<CR>", c.format_key("\r"))
    assert.equal("<CR>", c.format_key("\n"))
  end)
  it("maps tab, space, backspace", function()
    assert.equal("<Tab>", c.format_key("\t"))
    assert.equal("<Spc>", c.format_key(" "))
    assert.equal("<BS>", c.format_key("\x08"))
  end)
  it("passes through plain chars", function()
    assert.equal("a", c.format_key("a"))
    assert.equal("Z", c.format_key("Z"))
  end)
end)

describe("ui.common.mutator_summary_line", function()
  it("returns nil for empty input", function()
    assert.is_nil(c.mutator_summary_line(nil))
    assert.is_nil(c.mutator_summary_line({}))
  end)
  it("renders a single known mutator with its label", function()
    assert.equal("  Mutators: Iron", c.mutator_summary_line({ "iron" }))
  end)
  it("joins multiple mutators with comma-space", function()
    assert.equal("  Mutators: Iron, Glass, Rush",
      c.mutator_summary_line({ "iron", "glass", "rush" }))
  end)
  it("falls back to the raw name for unknown mutators", function()
    assert.equal("  Mutators: foo", c.mutator_summary_line({ "foo" }))
  end)
end)

describe("ui.common.pad_row", function()
  it("pads short content out to width", function()
    assert.equal("║hi    ║", c.pad_row("hi", 8))
  end)
  it("leaves content alone when it equals inner width", function()
    assert.equal("║abcd║", c.pad_row("abcd", 6))
  end)
  it("does not negative-pad when content overflows", function()
    assert.equal("║toolong║", c.pad_row("toolong", 6))
  end)
end)

describe("ui.common.make_border", function()
  it("returns top/sep/bot strings of the given character width", function()
    local b = c.make_border(10)
    assert.equal(10, char_width(b.top))
    assert.equal(10, char_width(b.sep))
    assert.equal(10, char_width(b.bot))
  end)
  it("uses the expected corner characters", function()
    local b = c.make_border(10)
    assert.is_truthy(b.top:match("^╔"))
    assert.is_truthy(b.top:match("╗$"))
    assert.is_truthy(b.sep:match("^╠"))
    assert.is_truthy(b.sep:match("╣$"))
    assert.is_truthy(b.bot:match("^╚"))
    assert.is_truthy(b.bot:match("╝$"))
  end)
  it("returns a row function that pads through pad_row", function()
    local b = c.make_border(8)
    assert.equal("║hi    ║", b.row("hi"))
  end)
end)

describe("ui.common.tier_room_bar", function()
  it("is all empty when nothing is cleared", function()
    assert.equal(string.rep("░", 8), c.tier_room_bar(0, 5, 8))
  end)
  it("is all filled when fully cleared", function()
    assert.equal(string.rep("█", 8), c.tier_room_bar(5, 5, 8))
  end)
  it("rounds proportional fill to nearest block", function()
    assert.equal(string.rep("█", 4) .. string.rep("░", 4),
      c.tier_room_bar(2, 4, 8))
  end)
  it("returns an all-empty bar when total is zero", function()
    assert.equal(string.rep("░", 8), c.tier_room_bar(0, 0, 8))
  end)
  it("defaults bar_len to 8 when omitted", function()
    assert.equal(8 * #"░", #c.tier_room_bar(0, 0))
  end)
end)

describe("ui.common.fmt_run_seconds", function()
  it("formats with one decimal and a trailing s", function()
    assert.equal("0.0s", c.fmt_run_seconds(0))
    assert.equal("12.3s", c.fmt_run_seconds(12.3))
    assert.equal("47.0s", c.fmt_run_seconds(47))
  end)
end)

describe("ui.common.streak_milestone_phrase", function()
  it("returns nil for sub-3 streaks", function()
    assert.is_nil(c.streak_milestone_phrase(0))
    assert.is_nil(c.streak_milestone_phrase(2))
  end)
  it("returns the right phrase at each threshold", function()
    assert.equal("Three in a row — streak bonus territory.",
      c.streak_milestone_phrase(3))
    assert.equal("Five deep — rhythm locked in.",
      c.streak_milestone_phrase(5))
    assert.equal("Double digits — you're flying.",
      c.streak_milestone_phrase(10))
    assert.equal("Dungeon legend — unreal streak.",
      c.streak_milestone_phrase(20))
  end)
  it("returns the highest matching tier for streaks above 20", function()
    assert.equal("Dungeon legend — unreal streak.",
      c.streak_milestone_phrase(42))
  end)
end)

describe("ui.common.xp_bar", function()
  it("is all empty at zero xp", function()
    assert.equal(string.rep("░", 8), c.xp_bar(0, 8))
  end)
  it("is all filled at max xp (1000)", function()
    assert.equal(string.rep("▓", 8), c.xp_bar(1000, 8))
  end)
  it("clamps to width when xp exceeds max", function()
    assert.equal(string.rep("▓", 8), c.xp_bar(99999, 8))
  end)
  it("renders proportional fill", function()
    assert.equal(string.rep("▓", 4) .. string.rep("░", 4),
      c.xp_bar(500, 8))
  end)
end)

describe("ui.common.build_optimal_lines", function()
  it("returns one short line for a regular room", function()
    local room = { optimal_keystrokes = { "d", "w" } }
    local out = c.build_optimal_lines(room, 80)
    assert.equal(1, #out)
    assert.equal("  d w", out[1])
  end)
  it("renders one line per phase for a boss room", function()
    local room = {
      is_boss = true,
      phases = {
        { optimal_keystrokes = { "d", "w" } },
        { optimal_keystrokes = { "y", "y", "p" } },
      },
    }
    local out = c.build_optimal_lines(room, 80)
    assert.equal(2, #out)
    assert.equal("  P1: d w", out[1])
    assert.equal("  P2: y y p", out[2])
  end)
  it("wraps long sequences to multiple lines", function()
    local ks = {}
    for i = 1, 30 do ks[i] = "x" end
    local room = { optimal_keystrokes = ks }
    local out = c.build_optimal_lines(room, 20)
    assert.is_true(#out >= 2)
    for _, ln in ipairs(out) do
      assert.is_true(#ln <= 20)
    end
  end)
end)

describe("ui.common.wrap_teach_text", function()
  it("returns an empty list for empty input", function()
    assert.same({}, c.wrap_teach_text("", 20))
    assert.same({}, c.wrap_teach_text(nil, 20))
  end)
  it("keeps short text on one line", function()
    assert.same({ "hello world" }, c.wrap_teach_text("hello world", 20))
  end)
  it("wraps at word boundaries", function()
    local out = c.wrap_teach_text("one two three four five", 10)
    assert.is_true(#out >= 2)
    for _, ln in ipairs(out) do
      assert.is_true(#ln <= 10)
    end
  end)
  it("trims leading and trailing whitespace", function()
    assert.same({ "x" }, c.wrap_teach_text("   x   ", 10))
  end)
end)

describe("ui.common.expand_keys", function()
  it("splits a multi-char token into single keys", function()
    assert.same({ "c", "i", "w" }, c.expand_keys({ "ciw" }))
  end)

  it("keeps <...> notation as one key", function()
    assert.same({ "<Esc>" }, c.expand_keys({ "<Esc>" }))
  end)

  it("expands a mixed sequence", function()
    assert.same({ "j", "$", "r", "5" }, c.expand_keys({ "j", "$", "r", "5" }))
  end)

  it("handles a token with text and a notation key", function()
    assert.same({ "c", "i", "w", "x", "<Esc>" },
      c.expand_keys({ "ciw", "x", "<Esc>" }))
  end)

  it("returns empty for empty input", function()
    assert.same({}, c.expand_keys({}))
    assert.same({}, c.expand_keys(nil))
  end)
end)
